version: '3.9'
services:
  api:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=1234567
      - DB_NAME=cashforce
      - DB_DIALECT=mysql
      - APP_ENV=development
      - PORT=3001
  db:
    image: mysql:8.0.28
    container_name: db
    ports: 
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234567
    restart: 'always'
